import type { Metadata } from "next";
import "./globals.css";
import { Container } from "@/components/Container";
import { Header } from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: {
    default: 'Car Sale',
    template: '%s | Car Sale'
  },
  description: "Generated by create next app",
};

type RootLayoutprops = {
  children: React.ReactNode
}

export default function RootLayout({children,}: Readonly<RootLayoutprops>) {
  return (
    <html lang="pt-BR" className="">
      <body>
        <Container>
          <Header />
            {children}
          <Footer />
        </ Container>
      </body>
    </html>
  );
}
