import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Car Sale",
  description: "Generated by create next app",
};

type RootLayoutprops = {
  children: React.ReactNode
}

export default function RootLayout({children,}: Readonly<RootLayoutprops>) {
  return (
    <html lang="pt-BR">
      <body>
        <header>header</header>
          <div>
            {children}
          </div>
        <footer>footer</footer>
      </body>
    </html>
  );
}
